@extends('layouts.app')
@section('content-app')
    @include('flash::message')
    @yield('content')
@endsection
@section('footer')
    <script
        src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous"></script>
    @stack('scripts-footer')
@endsection